sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install: 
  - openssl aes-256-cbc -K $encrypted_1234567890ab_key -iv $encrypted_1234567890ab_iv -in client-secret.json.enc -out client-secret.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file client-secret.json
  - gcloud config set project multik8s-480817
  - gcloud config set compute/zone us-central1
  - gcloud container clusters get-credentials multi-container-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t elpachanga1/multi-client -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true elpachanga1/multi-client npm test -- --coverage
after_success:
  - docker build -t elpachanga1/multi-client ./client
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: main