name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

env:
  GCP_PROJECT_ID: multik8s-480817
  GCP_ZONE: us-central1
  GKE_CLUSTER: multi-container-cluster
  DOCKER_USERNAME: elpachanga1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build test image
        run: docker build -t ${{ env.DOCKER_USERNAME }}/multi-client -f ./app/client/Dockerfile.dev ./app/client

      - name: Run tests
        run: docker run -e CI=true ${{ env.DOCKER_USERNAME }}/multi-client npm test -- --coverage

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          project_id: ${{ env.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Configure Docker to use gcloud as credential helper
        run: gcloud auth configure-docker

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} --zone ${{ env.GCP_ZONE }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker images
        run: |
          SHA=$(git rev-parse HEAD)
          docker build -t ${{ env.DOCKER_USERNAME }}/multi-client:latest -t ${{ env.DOCKER_USERNAME }}/multi-client:${SHA} -f ./app/client/Dockerfile ./app/client
          docker build -t ${{ env.DOCKER_USERNAME }}/multi-server:latest -t ${{ env.DOCKER_USERNAME }}/multi-server:${SHA} -f ./app/server/Dockerfile ./app/server
          docker build -t ${{ env.DOCKER_USERNAME }}/multi-worker:latest -t ${{ env.DOCKER_USERNAME }}/multi-worker:${SHA} -f ./app/worker/Dockerfile ./app/worker

      - name: Push Docker images
        run: |
          SHA=$(git rev-parse HEAD)
          docker push ${{ env.DOCKER_USERNAME }}/multi-client:latest
          docker push ${{ env.DOCKER_USERNAME }}/multi-server:latest
          docker push ${{ env.DOCKER_USERNAME }}/multi-worker:latest
          docker push ${{ env.DOCKER_USERNAME }}/multi-client:${SHA}
          docker push ${{ env.DOCKER_USERNAME }}/multi-server:${SHA}
          docker push ${{ env.DOCKER_USERNAME }}/multi-worker:${SHA}

      - name: Deploy to GKE
        run: |
          SHA=$(git rev-parse HEAD)
          kubectl apply -f k8s
          kubectl set image deployments/server-deployment server=${{ env.DOCKER_USERNAME }}/multi-server:${SHA}
          kubectl set image deployments/client-deployment client=${{ env.DOCKER_USERNAME }}/multi-client:${SHA}
          kubectl set image deployments/worker-deployment worker=${{ env.DOCKER_USERNAME }}/multi-worker:${SHA}
